version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 'sample'
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
